name: pictora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0  # QR code package
  path_provider: ^2.0.15  # Updated path provider package
  image_picker: ^0.8.7+4  # Image picker package

  permission_handler: ^10.2.0  # Permission handler package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.jpg
    - assets/hpbg1.png
